/**
 * Application Constants
 * Centralized content and configuration
 */

export const SITE_CONFIG = {
  name: 'Quỹ Bông Hồng Nhỏ',
  nameEn: 'Little Roses Foundation',
  shortName: 'LRF',
  tagline: 'Kết Nối Yêu Thương, Lan Tỏa Nhân Ái',
  mission: 'Nền văn minh tình thương',
  
  contact: {
    email: 'info@littlerosesfoundation.org',
    phone: '(+84) 906.22.04.22',
    phone2: '(+84) 896.62.24.22',
    address: '49 Pham Ngoc Thach St., Vo Thi Sau Ward, District 3, HCMC, Vietnam',
  },
  
  social: {
    facebook: 'https://facebook.com/littlerosefoundation',
    youtube: 'https://youtube.com/@littlerosefoundation',
    instagram: 'https://instagram.com/littlerosefoundation',
  },
  
  stats: {
    yearsActive: 3,
    childrenHelped: 5000,
    totalDonations: '73+ Tỷ',
    volunteers: 100,
    projects: 50,
  },
} as const;

export const NAVIGATION = [
  { id: 'home', label: 'Trang Chủ', path: '/', icon: 'home' },
  { id: 'about', label: 'Về Chúng Tôi', path: '/about', icon: 'info' },
  { id: 'programs', label: 'Dự Án', path: '/programs', icon: 'volunteer_activism' },
  { id: 'volunteers', label: 'Tình Nguyện', path: '/volunteers', icon: 'groups' },
  { id: 'news', label: 'Tin Tức', path: '/news', icon: 'article' },
  { id: 'finance', label: 'Tài Chính', path: '/finance', icon: 'account_balance' },
  { id: 'contact', label: 'Liên Hệ', path: '/contact', icon: 'mail' },
] as const;

export const CORE_VALUES = [
  {
    id: 'love',
    icon: 'favorite',
    title: 'Yêu Thương',
    description: 'Đặt tình thương làm gốc rễ cho mọi hành động và quyết định hỗ trợ.',
    color: 'text-rose-500',
    bgColor: 'bg-rose-50',
  },
  {
    id: 'transparency',
    icon: 'verified',
    title: 'Minh Bạch',
    description: 'Cam kết công khai mọi khoản đóng góp và chi tiêu tài chính rõ ràng.',
    color: 'text-blue-500',
    bgColor: 'bg-blue-50',
  },
  {
    id: 'dedication',
    icon: 'handshake',
    title: 'Tận Tâm',
    description: 'Làm việc với tinh thần trách nhiệm cao nhất vì lợi ích của trẻ em.',
    color: 'text-amber-500',
    bgColor: 'bg-amber-50',
  },
  {
    id: 'connection',
    icon: 'groups',
    title: 'Kết Nối',
    description: 'Lan tỏa và kết nối cộng đồng để tạo nên sức mạnh thay đổi lớn lao.',
    color: 'text-green-500',
    bgColor: 'bg-green-50',
  },
] as const;

export const IMPACT_AREAS = [
  {
    id: 'education',
    title: 'Giáo Dục',
    icon: 'school',
    description: 'Hỗ trợ học bổng, sách vở và xây dựng trường lớp khang trang cho trẻ em nghèo hiếu học.',
    color: 'primary',
    stats: { number: '2,500+', label: 'Học bổng' },
  },
  {
    id: 'healthcare',
    title: 'Y Tế & Sức Khỏe',
    icon: 'medical_services',
    description: 'Khám chữa bệnh miễn phí, cấp phát thuốc và hỗ trợ phẫu thuật tim cho bệnh nhi.',
    color: 'secondary',
    stats: { number: '1,000+', label: 'Ca phẫu thuật' },
  },
  {
    id: 'social',
    title: 'Bác Ái Xã Hội',
    icon: 'people',
    description: 'Cứu trợ thiên tai, tặng quà tết và chăm sóc người già neo đơn.',
    color: 'accent',
    stats: { number: '3,000+', label: 'Gia đình' },
  },
] as const;

export const PROGRAMS = [
  {
    id: 1,
    title: 'Xây Trường Cho Em',
    category: 'education',
    categoryLabel: 'Giáo dục',
    image: '/images/1.jpg',
    progress: 75,
    raised: 375000000,
    target: 500000000,
    donors: 342,
    description: 'Xây dựng trường học kiên cố cho 500 học sinh vùng cao tại Hà Giang',
    impact: '500 học sinh có phòng học mới',
    urgent: false,
    budgetBreakdown: [
      { item: 'Xây dựng 6 phòng học kiên cố', amount: 240000000, percentage: 48 },
      { item: 'Bàn ghế học sinh và thiết bị giảng dạy', amount: 80000000, percentage: 16 },
      { item: 'Nhà vệ sinh và khu vui chơi', amount: 60000000, percentage: 12 },
      { item: 'Hệ thống điện và chiếu sáng', amount: 40000000, percentage: 8 },
      { item: 'Sân chơi và hàng rào an toàn', amount: 50000000, percentage: 10 },
      { item: 'Chi phí giám sát và vận hành', amount: 30000000, percentage: 6 },
    ],
  },
  {
    id: 2,
    title: 'Phẫu Thuật Tim Miễn Phí',
    category: 'healthcare',
    categoryLabel: 'Y tế',
    image: '/images/2.jpg',
    progress: 90,
    raised: 900000000,
    target: 1000000000,
    donors: 678,
    description: 'Hỗ trợ phẫu thuật tim cho trẻ em nghèo bị bệnh tim bẩm sinh',
    impact: '50 ca phẫu thuật cứu sống trẻ em',
    urgent: true,
    budgetBreakdown: [
      { item: 'Chi phí phẫu thuật (50 ca x 15 triệu)', amount: 750000000, percentage: 75 },
      { item: 'Thuốc men và vật tư y tế', amount: 120000000, percentage: 12 },
      { item: 'Xét nghiệm và chẩn đoán trước mổ', amount: 50000000, percentage: 5 },
      { item: 'Chăm sóc sau phẫu thuật', amount: 40000000, percentage: 4 },
      { item: 'Hỗ trợ đi lại và ăn ở cho gia đình', amount: 30000000, percentage: 3 },
      { item: 'Quản lý dự án', amount: 10000000, percentage: 1 },
    ],
  },
  {
    id: 3,
    title: 'Học Bổng Vượt Khó',
    category: 'education',
    categoryLabel: 'Giáo dục',
    image: '/images/3.jpg',
    progress: 60,
    raised: 180000000,
    target: 300000000,
    donors: 234,
    description: 'Trao học bổng toàn phần cho 100 học sinh nghèo vượt khó xuất sắc',
    impact: '100 em tiếp tục ước mơ học hành',
    urgent: false,
    budgetBreakdown: [
      { item: 'Học phí toàn phần (100 em x 2 triệu/năm)', amount: 200000000, percentage: 67 },
      { item: 'Sách vở và dụng cụ học tập', amount: 40000000, percentage: 13 },
      { item: 'Đồng phục và giày dép', amount: 25000000, percentage: 8 },
      { item: 'Hỗ trợ ăn trưa tại trường', amount: 20000000, percentage: 7 },
      { item: 'Lớp học kỹ năng mềm và hướng nghiệp', amount: 10000000, percentage: 3 },
      { item: 'Giám sát và đánh giá học tập', amount: 5000000, percentage: 2 },
    ],
  },
  {
    id: 4,
    title: 'Cứu Trợ Thiên Tai',
    category: 'social',
    categoryLabel: 'Bác ái',
    image: '/images/4.jpg',
    progress: 45,
    raised: 90000000,
    target: 200000000,
    donors: 156,
    description: 'Hỗ trợ khẩn cấp lương thực và nhu yếu phẩm cho vùng lũ lụt miền Trung',
    impact: '1,000 gia đình được hỗ trợ khẩn cấp',
    urgent: true,
    budgetBreakdown: [
      { item: 'Gạo và lương thực khô (1,000 phần x 1.2 triệu)', amount: 120000000, percentage: 60 },
      { item: 'Nước uống sạch và thuốc sát trùng', amount: 20000000, percentage: 10 },
      { item: 'Quần áo, chăn màn và nồi nấu', amount: 30000000, percentage: 15 },
      { item: 'Thuốc men và vật tư y tế cơ bản', amount: 15000000, percentage: 7.5 },
      { item: 'Vận chuyển khẩn cấp đến vùng lũ', amount: 10000000, percentage: 5 },
      { item: 'Phối hợp và triển khai', amount: 5000000, percentage: 2.5 },
    ],
  },
  {
    id: 5,
    title: 'Dinh Dưỡng Cho Em',
    category: 'healthcare',
    categoryLabel: 'Y tế',
    image: '/images/5.jpg',
    progress: 55,
    raised: 82500000,
    target: 150000000,
    donors: 189,
    description: 'Cung cấp sữa và thực phẩm dinh dưỡng cho trẻ em suy dinh dưỡng',
    impact: '300 trẻ được cải thiện sức khỏe',
    urgent: false,
    budgetBreakdown: [
      { item: 'Sữa dinh dưỡng (300 em x 6 tháng)', amount: 90000000, percentage: 60 },
      { item: 'Thực phẩm bổ sung (trứng, thịt, rau)', amount: 30000000, percentage: 20 },
      { item: 'Vitamin và khoáng chất', amount: 12000000, percentage: 8 },
      { item: 'Khám sức khỏe định kỳ', amount: 10000000, percentage: 6.5 },
      { item: 'Tập huấn dinh dưỡng cho cha mẹ', amount: 5000000, percentage: 3.5 },
      { item: 'Giám sát chỉ số phát triển', amount: 3000000, percentage: 2 },
    ],
  },
  {
    id: 6,
    title: 'Tết Ấm No',
    category: 'social',
    categoryLabel: 'Bác ái',
    image: '/images/6.jpg',
    progress: 80,
    raised: 320000000,
    target: 400000000,
    donors: 567,
    description: 'Tặng quà Tết ý nghĩa cho người nghèo và trẻ em mồ côi',
    impact: '2,000 phần quà Tết ấm áp',
    urgent: false,
    budgetBreakdown: [
      { item: 'Gạo, dầu, đường (2,000 phần x 150k)', amount: 300000000, percentage: 75 },
      { item: 'Quần áo mới cho trẻ em', amount: 40000000, percentage: 10 },
      { item: 'Bánh kẹo và mứt Tết', amount: 30000000, percentage: 7.5 },
      { item: 'Tiền lì xì cho trẻ', amount: 20000000, percentage: 5 },
      { item: 'Vận chuyển và phân phối', amount: 7000000, percentage: 1.75 },
      { item: 'Tổ chức chương trình Tết', amount: 3000000, percentage: 0.75 },
    ],
  },
  {
    id: 7,
    title: 'Nhà Tình Thương',
    category: 'social',
    categoryLabel: 'Bác ái',
    image: '/images/7.jpg',
    progress: 35,
    raised: 175000000,
    target: 500000000,
    donors: 298,
    description: 'Xây nhà tình thương cho 20 hộ gia đình nghèo không có nhà ở',
    impact: '20 gia đình có mái ấm mới',
    urgent: false,
    budgetBreakdown: [
      { item: 'Xây dựng 20 căn nhà cấp 4 kiên cố (20 x 20 triệu)', amount: 400000000, percentage: 80 },
      { item: 'Vật tư nội thất cơ bản (giường, tủ, bàn)', amount: 40000000, percentage: 8 },
      { item: 'Hệ thống điện và nước sinh hoạt', amount: 30000000, percentage: 6 },
      { item: 'Nhà vệ sinh trong nhà', amount: 20000000, percentage: 4 },
      { item: 'Giấy tờ pháp lý và quyền sử dụng đất', amount: 7000000, percentage: 1.4 },
      { item: 'Giám sát và bảo hành', amount: 3000000, percentage: 0.6 },
    ],
  },
  {
    id: 8,
    title: 'Thư Viện Di Động',
    category: 'education',
    categoryLabel: 'Giáo dục',
    image: '/images/8.jpg',
    progress: 68,
    raised: 136000000,
    target: 200000000,
    donors: 412,
    description: 'Xe thư viện di động mang sách đến các vùng sâu vùng xa',
    impact: '50 trường học được phục vụ',
    urgent: false,
    budgetBreakdown: [
      { item: 'Mua và cải tạo xe tải thành thư viện', amount: 120000000, percentage: 60 },
      { item: 'Mua sách và tài liệu học tập (3,000 đầu sách)', amount: 40000000, percentage: 20 },
      { item: 'Kệ sách và trang bị nội thất xe', amount: 20000000, percentage: 10 },
      { item: 'Nhiên liệu và bảo dưỡng (1 năm)', amount: 12000000, percentage: 6 },
      { item: 'Lương thủ thư và tài xế (1 năm)', amount: 6000000, percentage: 3 },
      { item: 'Bảo hiểm và giấy phép hoạt động', amount: 2000000, percentage: 1 },
    ],
  },
  {
    id: 9,
    title: 'Nước Sạch Vùng Cao',
    category: 'healthcare',
    categoryLabel: 'Y tế',
    image: '/images/9.jpg',
    progress: 42,
    raised: 105000000,
    target: 250000000,
    donors: 187,
    description: 'Xây dựng hệ thống nước sạch cho các trường học vùng cao',
    impact: '800 học sinh có nước sạch',
    urgent: false,
    budgetBreakdown: [
      { item: 'Giếng khoan và hệ thống bơm nước (5 trường)', amount: 150000000, percentage: 60 },
      { item: 'Bể chứa và đường ống dẫn nước', amount: 50000000, percentage: 20 },
      { item: 'Hệ thống lọc và khử trùng', amount: 25000000, percentage: 10 },
      { item: 'Xây nhà vệ sinh và lavabo rửa tay', amount: 15000000, percentage: 6 },
      { item: 'Đào tạo sử dụng và bảo dưỡng', amount: 7000000, percentage: 2.8 },
      { item: 'Kiểm tra chất lượng nước định kỳ (1 năm)', amount: 3000000, percentage: 1.2 },
    ],
  },
  {
    id: 10,
    title: 'Mổ Mắt Từ Thiện',
    category: 'healthcare',
    categoryLabel: 'Y tế',
    image: '/images/10.jpg',
    progress: 85,
    raised: 255000000,
    target: 300000000,
    donors: 523,
    description: 'Phẫu thuật mắt miễn phí cho người già nghèo bị đục thủy tinh thể',
    impact: '150 ca phẫu thuật thành công',
    urgent: false,
    budgetBreakdown: [
      { item: 'Chi phí phẫu thuật (150 ca x 1.5 triệu)', amount: 225000000, percentage: 75 },
      { item: 'Kính mắt và thuốc sau mổ', amount: 30000000, percentage: 10 },
      { item: 'Xét nghiệm và chẩn đoán trước mổ', amount: 20000000, percentage: 6.5 },
      { item: 'Khám và chăm sóc sau phẫu thuật', amount: 15000000, percentage: 5 },
      { item: 'Hỗ trợ đi lại và ăn ở', amount: 7000000, percentage: 2.5 },
      { item: 'Quản lý và điều phối', amount: 3000000, percentage: 1 },
    ],
  },
  {
    id: 11,
    title: 'Xe Đạp Đến Trường',
    category: 'education',
    categoryLabel: 'Giáo dục',
    image: '/images/11.jpg',
    progress: 92,
    raised: 92000000,
    target: 100000000,
    donors: 678,
    description: 'Tặng xe đạp cho học sinh nghèo vùng xa phải đi bộ đến trường',
    impact: '200 em có xe đạp mới',
    urgent: false,
    budgetBreakdown: [
      { item: 'Xe đạp học sinh (200 chiếc x 400k)', amount: 80000000, percentage: 80 },
      { item: 'Phụ kiện: khóa, đèn, chuông, giỏ xe', amount: 10000000, percentage: 10 },
      { item: 'Bảo hiểm xe đạp (1 năm)', amount: 4000000, percentage: 4 },
      { item: 'Vận chuyển đến các xã vùng xa', amount: 3000000, percentage: 3 },
      { item: 'Lớp học an toàn giao thông', amount: 2000000, percentage: 2 },
      { item: 'Tổ chức lễ trao xe', amount: 1000000, percentage: 1 },
    ],
  },
  {
    id: 12,
    title: 'Chăm Sóc Người Già Neo Đơn',
    category: 'social',
    categoryLabel: 'Bác ái',
    image: '/images/12.jpg',
    progress: 58,
    raised: 145000000,
    target: 250000000,
    donors: 234,
    description: 'Hỗ trợ y tế và sinh hoạt cho người già cô đơn không nơi nương tựa',
    impact: '100 người già được chăm sóc',
    urgent: false,
    budgetBreakdown: [
      { item: 'Khám bệnh và thuốc men (100 người x 1 năm)', amount: 120000000, percentage: 48 },
      { item: 'Hỗ trợ sinh hoạt hàng tháng', amount: 60000000, percentage: 24 },
      { item: 'Chăm sóc tại nhà và đi lại', amount: 35000000, percentage: 14 },
      { item: 'Tổ chức sinh nhật và các ngày lễ', amount: 15000000, percentage: 6 },
      { item: 'Cải tạo nhà ở cơ bản', amount: 12000000, percentage: 4.8 },
      { item: 'Quản lý và giám sát chương trình', amount: 8000000, percentage: 3.2 },
    ],
  },
] as const;

export const NEWS = [
  {
    id: 1,
    title: 'Trao 100 suất học bổng cho học sinh vượt khó tại Hà Giang',
    excerpt: 'Chương trình đã mang niềm vui và động lực học tập cho các em học sinh nghèo vượt khó.',
    image: '/images/13.jpg',
    date: '2024-01-15',
    category: 'Giáo dục',
    author: 'Ban Biên Tập',
  },
  {
    id: 2,
    title: 'Phẫu thuật tim thành công cho 20 bệnh nhi nghèo',
    excerpt: 'Các ca phẫu thuật đã được thực hiện thành công, mang lại cơ hội sống mới.',
    image: '/images/14.jpg',
    date: '2024-01-10',
    category: 'Y tế',
    author: 'Bác sĩ Nguyễn Văn A',
  },
  {
    id: 3,
    title: 'Khánh thành trường học tại vùng cao Lai Châu',
    excerpt: 'Ngôi trường mới sẽ là nơi học tập an toàn và khang trang cho 300 học sinh.',
    image: '/images/15.jpg',
    date: '2024-01-05',
    category: 'Giáo dục',
    author: 'Ban Biên Tập',
  },
] as const;

export const TIMELINE = [
  {
    year: '01/11/2021',
    title: 'Thành lập chính thức',
    description: 'Little Roses Foundation (LRF) được thành lập theo Quyết định số 1151/QĐ-BNV, lấy cảm hứng từ truyền thống gia đình và tâm huyết thiện nguyện của Tập đoàn giáo dục Nguyễn Hoàng (NHG).',
  },
  {
    year: '22/04/2022',
    title: 'Cấp phép hoạt động toàn quốc',
    description: 'Bộ Nội Vụ chính thức cấp phép cho LRF hoạt động phi lợi nhuận trên phạm vi toàn quốc với mục tiêu chăm lo sức khỏe, giáo dục và hỗ trợ người có hoàn cảnh khó khăn.',
  },
  {
    year: '01/10/2022',
    title: 'Ra mắt công chúng',
    description: 'LRF chính thức ra mắt công chúng với sự kiện đấu giá gây quỹ và cam kết 73 tỷ đồng cho năm đầu tiên, khởi đầu hành trình "Nền văn minh tình thương".',
  },
  {
    year: '2023-2024',
    title: 'Xây dựng "Nhà Yêu Thương"',
    description: 'Triển khai các chương trình giúp đỡ người nghèo vượt nghịch cảnh, tạo cơ hội phát triển và xây dựng "Nhà Yêu Thương" trên khắp cả nước.',
  },
  {
    year: '2025',
    title: 'Tiếp tục phát triển',
    description: 'Mở rộng hoạt động với tôn chỉ "Nền văn minh tình thương", lan tỏa yêu thương và giá trị nhân bản đến cộng đồng.',
  },
] as const;

export const DONATION_TIERS = [
  {
    amount: 100000,
    title: 'Người Ủng Hộ',
    icon: 'favorite',
    benefits: ['Cảm ơn qua email', 'Chứng nhận điện tử'],
    color: 'gray',
  },
  {
    amount: 500000,
    title: 'Người Đồng Hành',
    icon: 'volunteer_activism',
    benefits: ['Tất cả ở mức trên', 'Cập nhật dự án hàng tháng', 'Ảnh & video chương trình'],
    color: 'primary',
    popular: true,
  },
  {
    amount: 1000000,
    title: 'Nhà Hảo Tâm',
    icon: 'workspace_premium',
    benefits: ['Tất cả ở mức trên', 'Giấy chứng nhận bằng giấy', 'Tham gia sự kiện VIP'],
    color: 'secondary',
  },
  {
    amount: 0,
    title: 'Tùy Chỉnh',
    icon: 'edit',
    benefits: ['Linh hoạt theo khả năng', 'Mọi đóng góp đều ý nghĩa'],
    color: 'accent',
  },
] as const;

// Mock Recent Donors - Những người ủng hộ gần đây
export const RECENT_DONORS = [
  { name: 'Nguyễn Văn A', amount: 5000000, program: 'Phẫu Thuật Tim Miễn Phí', time: '2 phút trước', isAnonymous: false },
  { name: 'Trần Thị B', amount: 2000000, program: 'Xây Trường Cho Em', time: '15 phút trước', isAnonymous: false },
  { name: 'Người ủng hộ ẩn danh', amount: 10000000, program: 'Cứu Trợ Thiên Tai', time: '28 phút trước', isAnonymous: true },
  { name: 'Lê Minh C', amount: 1000000, program: 'Học Bổng Vượt Khó', time: '45 phút trước', isAnonymous: false },
  { name: 'Phạm Thị D', amount: 500000, program: 'Dinh Dưỡng Cho Em', time: '1 giờ trước', isAnonymous: false },
  { name: 'Hoàng Văn E', amount: 3000000, program: 'Tết Ấm No', time: '1 giờ trước', isAnonymous: false },
  { name: 'Người ủng hộ ẩn danh', amount: 5000000, program: 'Nhà Tình Thương', time: '2 giờ trước', isAnonymous: true },
  { name: 'Đỗ Thị F', amount: 1500000, program: 'Thư Viện Di Động', time: '2 giờ trước', isAnonymous: false },
  { name: 'Vũ Văn G', amount: 2000000, program: 'Nước Sạch Vùng Cao', time: '3 giờ trước', isAnonymous: false },
  { name: 'Bùi Thị H', amount: 800000, program: 'Mổ Mắt Từ Thiện', time: '3 giờ trước', isAnonymous: false },
  { name: 'Ngô Văn I', amount: 1200000, program: 'Xe Đạp Đến Trường', time: '4 giờ trước', isAnonymous: false },
  { name: 'Người ủng hộ ẩn danh', amount: 7000000, program: 'Phẫu Thuật Tim Miễn Phí', time: '5 giờ trước', isAnonymous: true },
  { name: 'Đinh Thị K', amount: 500000, program: 'Chăm Sóc Người Già Neo Đơn', time: '5 giờ trước', isAnonymous: false },
  { name: 'Trương Văn L', amount: 3000000, program: 'Xây Trường Cho Em', time: '6 giờ trước', isAnonymous: false },
  { name: 'Dương Thị M', amount: 1000000, program: 'Học Bổng Vượt Khó', time: '7 giờ trước', isAnonymous: false },
] as const;

// Top Donors - Nhà hảo tâm tiêu biểu
export const TOP_DONORS = [
  { name: 'Công ty TNHH XYZ', amount: 100000000, totalDonations: 5, badge: 'platinum', message: 'Mong các em có tương lai tốt đẹp' },
  { name: 'Bà Nguyễn Thị Lan', amount: 50000000, totalDonations: 12, badge: 'gold', message: 'Trao cần câu hơn trao con cá' },
  { name: 'Ông Trần Văn Minh', amount: 30000000, totalDonations: 8, badge: 'gold', message: 'Hãy cho đi và bạn sẽ nhận lại gấp bội' },
  { name: 'Chị Phạm Thu Hà', amount: 20000000, totalDonations: 15, badge: 'silver', message: 'Yêu thương và san sẻ là hạnh phúc lớn nhất' },
  { name: 'Anh Lê Quang Huy', amount: 15000000, totalDonations: 10, badge: 'silver', message: 'Mỗi đóng góp nhỏ tạo nên thay đổi lớn' },
  { name: 'Nhóm Thiện Nguyện ABC', amount: 12000000, totalDonations: 6, badge: 'bronze', message: 'Cùng nhau vì một Việt Nam tốt đẹp hơn' },
] as const;

// Donor Testimonials - Lời tri ân từ người ủng hộ
export const DONOR_TESTIMONIALS = [
  {
    name: 'Chị Nguyễn Mai Anh',
    role: 'Nhà hảo tâm',
    amount: 10000000,
    program: 'Phẫu Thuật Tim Miễn Phí',
    testimonial: 'Tôi rất cảm động khi biết khoản đóng góp của mình đã giúp em bé Hoa được phẫu thuật tim thành công. Đây là niềm hạnh phúc lớn nhất của tôi.',
    avatar: 'https://i.pravatar.cc/150?img=1',
    date: '2024-01-10',
  },
  {
    name: 'Anh Trần Đức Thắng',
    role: 'Nhà đồng hành',
    amount: 5000000,
    program: 'Xây Trường Cho Em',
    testimonial: 'Từng là con của một gia đình nghèo, tôi hiểu được giá trị của giáo dục. Rất vui được góp phần xây dựng trường học cho các em.',
    avatar: 'https://i.pravatar.cc/150?img=12',
    date: '2024-01-08',
  },
  {
    name: 'Bà Lê Thị Hương',
    role: 'Người ủng hộ thường xuyên',
    amount: 2000000,
    program: 'Học Bổng Vượt Khó',
    testimonial: 'Quỹ rất minh bạch và tận tâm. Tôi yên tâm mỗi tháng đóng góp vì biết tiền đến đúng nơi cần giúp đỡ.',
    avatar: 'https://i.pravatar.cc/150?img=5',
    date: '2024-01-05',
  },
  {
    name: 'Công ty ABC Tech',
    role: 'Đối tác doanh nghiệp',
    amount: 50000000,
    program: 'Nhiều dự án',
    testimonial: 'Là doanh nghiệp, chúng tôi tin vào trách nhiệm xã hội. Partnership với LRF giúp chúng tôi lan tỏa yêu thương đến cộng đồng.',
    avatar: 'https://i.pravatar.cc/150?img=20',
    date: '2024-01-01',
  },
] as const;

// Volunteers - Tình nguyện viên
export const VOLUNTEERS = [
  {
    id: 1,
    name: 'Nguyễn Văn Minh',
    role: 'Trưởng nhóm Y tế',
    avatar: 'https://i.pravatar.cc/150?img=13',
    joined: '2020-05-15',
    hours: 450,
    programs: ['Phẫu Thuật Tim Miễn Phí', 'Khám Sức Khỏe Định Kỳ'],
    bio: 'Bác sĩ nội khoa với 10 năm kinh nghiệm, tận tâm với công tác từ thiện',
    location: 'Hà Nội',
  },
  {
    id: 2,
    name: 'Trần Thị Lan',
    role: 'Giáo viên Tình nguyện',
    avatar: 'https://i.pravatar.cc/150?img=9',
    joined: '2019-08-20',
    hours: 680,
    programs: ['Xây Trường Cho Em', 'Học Bổng Vượt Khó'],
    bio: 'Giáo viên tiểu học, đam mê mang kiến thức đến vùng cao',
    location: 'TP.HCM',
  },
  {
    id: 3,
    name: 'Lê Quang Huy',
    role: 'Nhiếp ảnh gia',
    avatar: 'https://i.pravatar.cc/150?img=14',
    joined: '2021-03-10',
    hours: 320,
    programs: ['Tất cả các dự án'],
    bio: 'Chuyên viên truyền thông, ghi lại những khoảnh khắc ý nghĩa',
    location: 'Đà Nẵng',
  },
  {
    id: 4,
    name: 'Phạm Thị Hương',
    role: 'Điều phối viên',
    avatar: 'https://i.pravatar.cc/150?img=10',
    joined: '2018-11-01',
    hours: 920,
    programs: ['Cứu Trợ Thiên Tai', 'Tết Ấm No'],
    bio: 'Quản lý dự án chuyên nghiệp, kỹ năng tổ chức xuất sắc',
    location: 'Hà Nội',
  },
  {
    id: 6,
    name: 'Đỗ Thị Mai',
    role: 'Nhân viên Y tế',
    avatar: 'https://i.pravatar.cc/150?img=8',
    joined: '2019-12-15',
    hours: 480,
    programs: ['Dinh Dưỡng Cho Em', 'Mổ Mắt Từ Thiện'],
    bio: 'Y tá với trái tim nhân ái, chăm sóc trẻ em nghèo',
    location: 'Cần Thơ',
  },
  {
    id: 7,
    name: 'Vũ Minh Tú',
    role: 'Tài xế Tình nguyện',
    avatar: 'https://i.pravatar.cc/150?img=16',
    joined: '2021-01-20',
    hours: 390,
    programs: ['Thư Viện Di Động', 'Xe Đạp Đến Trường'],
    bio: 'Lái xe chuyên nghiệp, vận chuyển hàng cứu trợ đến vùng xa',
    location: 'Long An',
  },
  {
    id: 8,
    name: 'Bùi Thị Nga',
    role: 'Tình nguyện viên Dịch thuật',
    avatar: 'https://i.pravatar.cc/150?img=7',
    joined: '2020-09-10',
    hours: 280,
    programs: ['Tất cả các dự án'],
    bio: 'Biên phiên dịch, hỗ trợ giao tiếp với đối tác quốc tế',
    location: 'Hà Nội',
  },
] as const;

// Program Updates - Cập nhật tiến độ dự án
export const PROGRAM_UPDATES = [
  {
    programId: 1,
    date: '2024-01-15',
    title: 'Phẫu thuật thành công cho em Hoa',
    description: 'Em Hoa đã được phẫu thuật tim thành công và hiện đang trong giai đoạn hồi phục tốt.',
    image: '/images/14.jpg',
    type: 'success',
  },
  {
    programId: 1,
    date: '2024-01-10',
    title: 'Khám sàng lọc cho 50 em',
    description: 'Đội ngũ y bác sĩ đã tiến hành khám sàng lọc tim mạch cho 50 em tại Sapa.',
    image: '/images/2.jpg',
    type: 'update',
  },
  {
    programId: 2,
    date: '2024-01-12',
    title: 'Khởi công trường tiểu học Tả Van',
    description: 'Dự án xây trường mới tại Tả Van đã chính thức khởi công với sự tham gia của cộng đồng địa phương.',
    image: '/images/1.jpg',
    type: 'milestone',
  },
  {
    programId: 3,
    date: '2024-01-14',
    title: 'Trao 100 suất học bổng',
    description: 'Chúng tôi đã trao tặng 100 suất học bổng cho học sinh nghèo vượt khó tại 5 tỉnh miền núi.',
    image: '/images/13.jpg',
    type: 'success',
  },
] as const;

export const SPONSORS = [
  {
    id: 1,
    name: 'Deloitte',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2023/03/deloitte.png',
    url: 'https://www2.deloitte.com/vn/en.html',
  },
  {
    id: 2,
    name: 'Sacombank',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2022/09/scb.png',
    url: 'https://www.sacombank.com.vn/Pages/default.aspx',
  },
  {
    id: 3,
    name: 'Kamala',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2022/09/kamala.png',
    url: 'https://kamala.vn/',
  },
  {
    id: 4,
    name: 'MIA',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2022/09/mia.png',
    url: 'http://mia.com.vn/',
  },
  {
    id: 5,
    name: 'MSB',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2022/09/msb.png',
    url: 'https://www.msb.com.vn/',
  },
  {
    id: 6,
    name: 'NTS',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2022/09/nts.png',
    url: 'https://masothue.com/0302204313-cong-ty-tnhh-nts',
  },
  {
    id: 7,
    name: 'PVI',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2022/09/pvi.png',
    url: 'https://baohiempvi.com/',
  },
  {
    id: 8,
    name: 'PwC',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2022/09/pwc.png',
    url: 'https://www.pwc.com/',
  },
  {
    id: 9,
    name: 'THP',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2022/09/thp.png',
    url: 'https://www.thp.com.vn/',
  },
  {
    id: 10,
    name: 'VVN',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2022/09/vvn.png',
    url: '',
  },
  {
    id: 11,
    name: 'Luật Việt',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2023/03/luatviet.png',
    url: 'https://www.dentonsluatviet.com/',
  },
  {
    id: 12,
    name: 'Việt Thương',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2023/03/vietthuong.png',
    url: 'https://vietthuong.vn/',
  },
  {
    id: 13,
    name: 'Bravo',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2023/03/bravo.png',
    url: 'https://www.bravo.com.vn/',
  },
  {
    id: 14,
    name: 'SCB',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2023/03/scb.png',
    url: 'https://www.scb.com.vn/',
  },
  {
    id: 15,
    name: 'Trường Hoàng Phát',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2023/03/truong-hoang-phat.png',
    url: 'https://banghehocsinhgiare.com/',
  },
  {
    id: 16,
    name: 'Indochine Counsel',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2023/03/indochine.png',
    url: 'https://www.indochinecounsel.com/',
  },
  {
    id: 17,
    name: 'Microsoft',
    logo: 'https://littlerosesfoundation.org/wp-content/uploads/2023/03/Microsoft.png',
    url: 'https://www.microsoft.com/vi-vn/',
  },
] as const;
